require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "tmp/*"
    - "vendor/**/*"

Gemspec/RequiredRubyVersion:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/HashAlignment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyClass:
  AllowComments: true

Lint/EmptyWhen:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RedundantMerge:
  Enabled: true
  MaxKeyValuePairs: 1

Performance/RedundantStringChars:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RaiseArgs:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/WordArray:
  Enabled: false
