name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        name: Setup Ruby
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.0.0
          - 2.1
          - 2.2
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 3.0.0
          - 3.1
    steps:
      - uses: actions/checkout@v3
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        name: Set up Ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rspec
